apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: citizendemo
spec:
  replicas: 1
  selector:
    matchLabels:
      service: loadgenerator
  template:
    metadata:
      labels:
        service: loadgenerator
    spec:
      containers:
        - name: loadgenerator
          image: cdjtestacr.azurecr.io/loadgenerator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: citizenapi
  namespace: citizendemo
spec:
  type: LoadBalancer
  selector:
    service: citizenapi
  ports:
    - name: "5004"
      protocol: TCP
      port: 5004
      targetPort: 5004