apiVersion: v1
kind: ConfigMap
metadata:
  name: ama-metrics-prometheus-config
  namespace: kube-system
data:
  prometheus-config: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: mongodb-metrics
        static_configs:
          - targets: ['mongodb.citizendemo.svc.cluster.local:9216']
      - job_name: kafka-metrics
        static_configs:
          - targets: ['kafka.citizendemo.svc.cluster.local:9308']
      - job_name: citizenapi-metrics
        static_configs:
          - targets: ['citizenapi.citizendemo.svc.cluster.local:5001']
      - job_name: resourceapi-metrics
        static_configs:
          - targets: ['resourceapi.citizendemo.svc.cluster.local:5002']
      - job_name: provisionworker-metrics
        static_configs:
          - targets: ['provisionworker.citizendemo.svc.cluster.local:5003']
      - job_name: loadgenerator-metrics
        static_configs:
          - targets: ['loadgenerator.citizendemo.svc.cluster.local:5004']