apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: citizendemo
spec:
  replicas: 1
  selector:
    matchLabels:
      service: jaeger
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: jaeger
    spec:
      containers:
        - env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
          image: jaegertracing/all-in-one:latest
          name: jaeger
          ports:
            - containerPort: 16686
            - containerPort: 4317
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: citizendemo
spec:
  type: LoadBalancer
  selector:
    service: jaeger
  ports:
    - name: "16686"
      protocol: TCP
      port: 16686
      targetPort: 16686
    - name: "4317"
      protocol: TCP
      port: 4317
      targetPort: 4317

