apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: citizendemo
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: kafka
    spec:
      hostname: kafka
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: kafka-zookeeper:2181
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
          securityContext:
            runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: citizendemo
spec:
  type: LoadBalancer
  selector:
    service: kafka
  ports:
    - name: "9092"
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: "9308"
      protocol: TCP
      port: 9308
      targetPort: 9308
