apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: citizendemo
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: citizendemo
            - name: MONGO_INITDB_ROOT_USERNAME
              value: citizendemo
        - name: mongodb-metrics
          image: percona/mongodb_exporter:0.39.0
          args:
            - --mongodb.uri=mongodb://citizendemo:citizendemo@localhost:27017
            - --compatible-mode
            - --discovering-mode
            - --mongodb.collstats-colls=CitizenDemo.citizens,CitizenDemo.resources
            - --collector.diagnosticdata
            - --collector.replicasetstatus
            - --collector.dbstats
            - --collector.topmetrics
            - --collector.indexstats
            - --collector.collstats
          ports:
            - containerPort: 9216
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: citizendemo
spec:
  type: LoadBalancer
  selector:
    service: mongodb
  ports:
    - name: "27017"
      protocol: TCP
      port: 27017
      targetPort: 27017
    - name: "9216"
      protocol: TCP
      port: 9216
      targetPort: 9216

