apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: citizendemo
data:
  prometheus-config.yaml: |
    global:
      scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      scrape_timeout: 10s # scrape_timeout - global default is 10s.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
    scrape_configs:
      - job_name: 'mongodb-metrics'
        static_configs:
          - targets: ['mongodb:9216']
      - job_name: 'kafka-metrics'
        static_configs:
          - targets: ['kafka:9308']
      - job_name: "citizenapi-metrics"
        metrics_path: /metrics
        scheme: http
        honor_timestamps: true
        honor_labels: true
        static_configs:
          - targets: [ 'citizenapi:5001' ]
      - job_name: "resourceapi-metrics"
        metrics_path: /metrics
        scheme: http
        honor_timestamps: true
        honor_labels: true
        static_configs:
          - targets: [ 'resourceapi:5002' ]
      - job_name: "provisionworker-metrics"
        metrics_path: /metrics
        scheme: http
        honor_timestamps: true
        honor_labels: true
        static_configs:
          - targets: [ 'provisionworker:5003']
      - job_name: "loadgenerator-metrics"
        metrics_path: /metrics
        scheme: http
        honor_timestamps: true
        honor_labels: true
        static_configs:
          - targets: [ 'loadgenerator:5004']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: citizendemo
spec:
  replicas: 1
  selector:
    matchLabels:
      service: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: prometheus
    spec:
      containers:
        - args:
            - --config.file=/etc/prometheus/prometheus-config.yaml
          image: prom/prometheus:latest
          name: prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
      restartPolicy: Always
      volumes:
        - name: prometheus-config
          configMap:
            name:
              prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: citizendemo
spec:
  type: LoadBalancer
  selector:
    service: prometheus
  ports:
    - name: "9090"
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-mesh
  namespace: citizendemo
spec:
  type: ExternalName
  externalName: prometheus.istio-system.svc.cluster.local
  ports:
    - name: "9090"
      protocol: TCP
      port: 9090
      targetPort: 9090
