FROM maven
COPY ./ ./
RUN mvn clean package
EXPOSE 5003
ADD https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar .
CMD ["java", "-javaagent:/opentelemetry-javaagent.jar", "-Dotel.resource.attributes=service.name=citizendemo.provisionworker", "-Dotel.exporter.otlp.endpoint=http://host.docker.internal:4317", "-jar", "target/provisionworker-0.0.1-SNAPSHOT.jar"]