FROM maven
COPY ./ ./
RUN mvn clean package
ADD https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar .
EXPOSE 5004
CMD ["java", "-jar", "target/loadgenerator-0.0.1-SNAPSHOT.jar"]