{
 "title": "CitizenDemo",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  { "title": "CitizenDemo Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests/Second by Service URI",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(uri) (irate(http_server_requests_seconds_count[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Status Codes by Service",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status, job) (irate(http_server_requests_seconds_count[$__rate_interval]))",
     "legendFormat": "{{status}}-{{job}}"
    }
   ]
  },
  {
   "title": "Latency by Outcome",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(outcome,job) (increase(http_server_requests_seconds_sum[$__rate_interval]))\n / \n (sum by(outcome,job) (increase(http_server_requests_seconds_count[$__rate_interval])) != 0)",
     "legendFormat": "{{outcome}}-{{job}}"
    }
   ]
  },
  {
   "title": "End-To-End Provisioning Latency SLI",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "citizendemo_provisionworker_provisioninglatency_seconds_sum/citizendemo_provisionworker_provisioninglatency_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Longest Requests",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, max (max_over_time(http_server_requests_seconds_max[$__range])) by(uri, outcome, method))"
    },
    {
     "expr": "sum (increase(http_server_requests_seconds_count[$__range])) by(uri, outcome, method)"
    },
    {
     "expr": "sum by(uri, outcome, method) (\n    increase(http_server_requests_seconds_sum[$__range])\n)\n/ \nsum by(uri, outcome, method) (\n    increase(http_server_requests_seconds_count[$__range])\n)"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by(exception, job) (increase(http_server_requests_seconds_count{exception!=\"None\"}[$__range]))) > 0"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(\n    sum by (method, uri, exception, status, job) (\n        increase(\n            http_server_requests_seconds_count{status=~\"5..|400|499\"}[$__range]\n        )\n    ) > 0, \n    'uri', \n    '$1/*$2', \n    'uri', \n    '(.*)\\\\/\\\\{.+\\\\}(.*)'\n)"
    }
   ]
  },
  { "title": "CitizenDemo Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 23 },
   "targets": [
    { "service": "citizendemo.provisionworker" }
   ]
  },
  {
   "title": "Trace Duration Histogram",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 23 },
   "targets": [
    { "service": "citizendemo.provisionworker" }
   ]
  },
  { "title": "CitizenDemo Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Logs Timeline",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(count_over_time({logstream=\"stdout\"} |~ \"$search\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "{logstream=\"stdout\"} |~ \"$search\""
    }
   ]
  },
  { "title": "JVM, HTTP, GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "HTTP - Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "HTTP - Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{status!~\"5..\"}[1m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{status!~\"5..\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "system_cpu_usage{}", "legendFormat": "system" },
    { "expr": "process_cpu_usage{}", "legendFormat": "process" },
    {
     "expr": "avg_over_time(process_cpu_usage{}[15m])",
     "legendFormat": "process-15m"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "system_load_average_1m{}", "legendFormat": "system-1m" },
    { "expr": "system_cpu_count{}", "legendFormat": "cpus" }
   ]
  },
  {
   "title": "Garbage Collections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{}[1m])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Garbage Collection - Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{}[1m])/rate(jvm_gc_pause_seconds_count{}[1m])",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    { "expr": "jvm_gc_pause_seconds_max{}", "legendFormat": "max {{action}} ({{cause}})" }
   ]
  },
  { "title": "MongoDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "rate(mongodb_collstats_latencyStats_reads_latency[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Writes Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 66 },
   "targets": [
    {
     "expr": "rate(mongodb_collstats_latencyStats_writes_latency[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 66 },
   "targets": [
    {
     "expr": "rate(mongodb_collstats_latencyStats_transactions_latency[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Efficiency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(mongodb_mongod_metrics_query_executor_total{state=\"scanned_objects\"}[5m]))/sum(increase(mongodb_mongod_metrics_document_total{state=\"returned\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(mongodb_mongod_metrics_query_executor_total{state=\"scanned\"}[5m]))/sum(increase(mongodb_mongod_metrics_document_total{state=\"returned\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scanned and Moved Objects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ops/s" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total[5m]) or irate(mongodb_mongod_metrics_query_executor_total[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_record_moves_total[5m]) or irate(mongodb_mongod_metrics_record_moves_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Operations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 80 },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_document_total[5m]) or \nirate(mongodb_mongod_metrics_document_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_connections{state=\"current\"}"
    }
   ]
  },
  {
   "title": "Objects",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 80 },
   "targets": [
    { "expr": "mongodb_dbstats_objects", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 80 },
   "targets": [
    {
     "expr": "mongodb_memory{type=~\"resident|virtual\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_connections{state=\"available\"}"
    }
   ]
  }
 ]
}